-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

-- Modify this code to update the DB schema diagram.
-- To reset the sample schema, replace everything with
-- two dots ('..' - without quotes).

CREATE TABLE "Income" (
    "symbol" varchar,
    "date" varchar,
    "reportedCurrency" varchar,
    "cik" varchar,
    "fillingDate" varchar,
    "acceptedDate" varchar,
    "calendarYear" int,
    "period" varchar,
    "revenue" float,
    "costOfRevenue" float,
    "grossProfit" float,
    "grossProfitRatio" float,
    "researchAndDevelopmentExpenses" float,
    "generalAndAdministrativeExpenses" float,
    "sellingAndMarketingExpenses" float,
    "sellingGeneralAndAdministrativeExpenses" float,
    "otherExpenses" float,
    "operatingExpenses" float,
    "costAndExpenses" float,
    "interestIncome" float,
    "interestExpense" float,
    "depreciationAndAmortization" float,
    "ebitda" float,
    "ebitdaratio" float,
    "operatingIncome" float,
    "operatingIncomeRatio" float,
    "totalOtherIncomeExpensesNet" float,
    "incomeBeforeTax" float,
    "incomeBeforeTaxRatio" float,
    "incomeTaxExpense" float,
    "netIncome" float,
    "netIncomeRatio" float,
    "eps" float,
    "epsdiluted" float,
    "weightedAverageShsOut" float,
    "weightedAverageShsOutDil" float,
    "link" varchar   
    "finalLink" varchar   
);

CREATE TABLE "cashflows" (
    "symbol" varchar,
    "date" varchar,
    "reportedCurrency" varchar,
    "cik" varchar,
    "fillingDate" varchar,
    "acceptedDate" varchar,
    "calendarYear" int,
    "period" varchar,
    "netIncome" money,
    "depreciationAndAmortization" float,
    "deferredIncomeTax" float,
    "stockBasedCompensation" float,
    "changeInWorkingCapital" float,
    "accountsReceivables" float,
    "inventory" float,
    "accountsPayables" float,
    "otherWorkingCapital" float,
    "otherNonCashItems" float,
    "netCashProvidedByOperatingActivities" float,
    "investmentsInPropertyPlantAndEquipment" float,
    "acquisitionsNet" float,
    "purchasesOfInvestments" float,
    "salesMaturitiesOfInvestments" float,
    "otherInvestingActivites" float,
    "netCashUsedForInvestingActivites" float,
    "debtRepayment" float,
    "commonStockIssued" float,
    "commonStockRepurchased" float,
    "dividendsPaid" float,
    "otherFinancingActivites" float,
    "netCashUsedProvidedByFinancingActivities" float,
    "effectOfForexChangesOnCash" float,
    "netChangeInCash" float,
    "cashAtEndOfPeriod" float,
    "cashAtBeginningOfPeriod" float,
    "operatingCashFlow" float,
    "capitalExpenditure" float,
    "freeCashFlow" float,
    "link" varchar
    "finalLink" varchar   
);

CREATE TABLE "balance" (
    "date" varchar,
    "symbol" varchar,
    "reportedCurrency" varchar,
    "cik" varchar,
    "fillingDate" varchar,
    "acceptedDate" varchar,
    "calendarYear" int,
    "period" varchar,
    "cashAndCashEquivalents" float,
    "shortTermInvestments" float,
    "cashAndShortTermInvestments" float,
    "netReceivables" float,
    "inventory" float,
    "otherCurrentAssets" float,
    "totalCurrentAssets" float,
    "propertyPlantEquipmentNet" float,
    "goodwill" float,
    "intangibleAssets" float,
    "goodwillAndIntangibleAssets" float,
    "longTermInvestments" float,
    "taxAssets" float,
    "otherNonCurrentAssets" float,
    "totalNonCurrentAssets" float,
    "otherAssets" float,
    "totalAssets" float,
    "accountPayables" float,
    "shortTermDebt" float,
    "taxPayables" float,
    "deferredRevenue" float,
    "otherCurrentLiabilities" float,
    "totalCurrentLiabilities" float,
    "longTermDebt" float,
    "deferredRevenueNonCurrent" float,
    "deferredTaxLiabilitiesNonCurrent" float,
    "otherNonCurrentLiabilities" float,
    "totalNonCurrentLiabilities" float,
    "otherLiabilities" float,
    "capitalLeaseObligations" float,
    "totalLiabilities" float,
    "preferredStock" float,
    "commonStock" float,
    "retainedEarnings" float,
    "accumulatedOtherComprehensiveIncomeLoss" float,
    "othertotalStockholdersEquity" float,
    "totalStockholdersEquity" float,
    "totalLiabilitiesAndStockholdersEquity" float,
    "minorityInterest" float,
    "totalEquity" float,
    "totalLiabilitiesAndTotalEquity" float,
    "totalInvestments" float,
    "totalDebt" float,
    "netDebt" float,
    "link" varchar
    "finalLink" varchar   
);


